version: '3.3'
services:
  mymariadb:
    container_name: mymariadb 
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD= password
    ports:
      - 3306:3306
    volumes:
      - sagar-volume:/var/lib/mysql
  mypostgres:
    container_name: mypostgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD= password
    ports:
      - 5432:5432
    volumes:
      - sagar-volume:/var/lib/postgresql/data
  mypush:
    container_name: mypush
    image: hemsagar1994/mypush
    environment:
      - spring.profiles.active=${SPRING_PROFILES_ACTIVE}
      - spring.datasource.password= password
      - spring.datasource.url=${SPRING_DATASOURCE_URL}
    ports:
      - "8080:8080"
    links:
      - mymariadb
      - mypostgres
  mypop:
    container_name: mypop
    image: hemsagar1994/mypop
    environment:
      - spring.profiles.active=${SPRING_PROFILES_ACTIVE}
      - spring.datasource.password= password
      - spring.datasource.url=${SPRING_DATASOURCE_URL}
    ports:
      - 8081:8081
    links:
      - mymariadb
      - mypostgres
volumes: 
  sagar-volume: {}
