apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypostgres
  labels:
    environment: postgres_db
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: postgres_db
  template:
    metadata:
      labels:
        environment: postgres_db
    spec:
      containers:
       - name: mypostgresdb
         image: postgres
         ports:
         - containerPort: 5432
         env:
         - name: POSTGRES_PASSWORD
           value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mypostgresdb-service
spec:
  selector:
    environment: postgres_db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
